### ISSUE TITLE
Popup not closing after upload finishes

### ISSUE THREAD

**Issue by ankitkalia1195** [rafayet-monon/google-search-extractor#24] opened 2020-03-30 09:10 UTC
![Screen Shot 2020-03-30 at 4 01 37 PM](https://user-images.githubusercontent.com/11224179/77895356-d6a9af80-72a0-11ea-9725-5653c40e0392.png)

The popup does not close when the csv upload finishes and user does not see any message also.

**Comment by rafayet-monon** [comment] 2020-03-30 10:47
Hi,

As you know I used chromedriver/selenium to parse the google search page and deployed the application in Heroku free tier.

And I also used `Sidekiq` so that this time consuming task can be run in background. 

As I mentioned in this [section](https://github.com/rafayet-monon/google-search-extractor#see-it-live) of the Readme that 

`As redis is a service that requires credit cards info to work in heroku and I don't have one so file uploading and searching using Sidekiq is not available there. The search is done in runtime after uploading the file.`

I added the configuration to check if the application is running in production then the searching will also be done synchronously rather than running in background in async sidekiq.

So, The issue is expected, which I also faced and the possible reason for this is the searching and parsing is taking it's time and the modal should close after the whole request. of uploading and searching is completed.

That is why I requested not to upload CSV file with large keyword set in heroku. 

In this particular case of using free tier of heroku even if I use something other than chromedriver/selenium is supposed to take the time.

Closing this issue. Please reopen it if you feel that the case I pointed is not right.

**Closed by rafayet-monon** 2020-03-30 10:47 UTC
